name: CI

on:
  push:
    paths-ignore: ['**/*.md']
  pull_request:
    paths-ignore: ['**/*.md']

jobs:
  linux:
    uses: ./.github/workflows/linux.yml
    permissions:
      contents: write

  macOS:
    uses: ./.github/workflows/macos.yml

  windows:
    uses: ./.github/workflows/windows.yml

  release:
    needs: [linux, macos, windows]
    uses: ./.github/workflows/release.yml
    permissions:
      contents: write
