name: Linux

on:
  workflow_call:

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup V
        run: |
          curl -Lo v_linux.zip https://github.com/vlang/v/releases/latest/download/v_linux.zip
          unzip -o v_linux.zip
          mv v ~/v
          ~/v/v symlink
      - run: v install
      - name: Save cache
        uses: actions/cache/save@v4
        with:
          path: |
            ~/v
            ~/.vmodules
          key: ${{ runner.os }}-${{ github.sha }}

  lint:
    needs: setup
    uses: ./.github/workflows/lint.yml

  test:
    needs: setup
    strategy:
      matrix:
        cc: [tcc, gcc, clang]
        optimization: ['', '-W'] # ['', '-W -cstrict']` # cstrict currently fails with pcre
        exclude:
          - cc: tcc
            optimization: '-W' # ['', '-W -cstrict']`
      fail-fast: false
    runs-on: ubuntu-latest
    env:
      VFLAGS: -cg -cc ${{ matrix.cc }} ${{ matrix.optimization }}
    steps:
      - uses: actions/checkout@v4
      - name: Restore cache
        uses: actions/cache/restore@v4
        with:
          path: |
            ~/v
            ~/.vmodules
          key: ${{ runner.os }}-${{ github.sha }}
          fail-on-cache-miss: true
      - name: Setup V
        run: ~/v/v symlink && v -showcc self && v doctor
      - name: Build
        run: v -o lvb .
      - name: Run
        run: ./lvb .

  test-sanitzed:
    needs: setup
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - cc: gcc
            sanitizer: thread
          - cc: gcc
            sanitizer: address,leak,undefined,shift,shift-exponent,shift-base,integer-divide-by-zero,unreachable,vla-bound,null,return,signed-integer-overflow,bounds,bounds-strict,alignment,object-size,float-divide-by-zero,float-cast-overflow,nonnull-attribute,returns-nonnull-attribute,bool,enum,vptr
          - cc: clang
            sanitizer: address,leak,undefined
          - cc: clang
            sanitizer: thread
          - cc: clang
            sanitizer: memory
      fail-fast: false
    env:
      VFLAGS: -cg -cc ${{ matrix.cc }}
    steps:
      - uses: actions/checkout@v4
      - name: Restore cache
        uses: actions/cache/restore@v4
        with:
          path: |
            ~/v
            ~/.vmodules
          key: ${{ runner.os }}-${{ github.sha }}
          fail-on-cache-miss: true
      - name: Setup V
        run: ~/v/v symlink && v -showcc self && v doctor
      - name: Setup zig
        uses: goto-bus-stop/setup-zig@v2
      - name: Build
        run: v -cflags -fsanitize=${{ matrix.sanitizer }} -o lvb .
      - name: Run
        run: ./lvb .

  deploy-example:
    needs: test
    runs-on: ubuntu-latest
    permissions:
      contents: write
    env:
      VFLAGS: -cc gcc -prod
      ARTIFACT: gui_project-linux-amd64
    steps:
      - uses: actions/checkout@v4
      - name: Restore cache
        uses: actions/cache/restore@v4
        with:
          path: |
            ~/v
            ~/.vmodules
          key: ${{ runner.os }}-${{ github.sha }}
          fail-on-cache-miss: true
      - name: Setup V
        run: ~/v/v symlink && ~/v/v -showcc self
      - name: Install dependencies
        run: |
          sudo apt install -y -qq libgtk-3-dev libwebkit2gtk-4.0-dev
          cd examples/gui_project
          v install
          ~/.vmodules/ttytm/webview/build.vsh --silent
      - name: Build
        run: |
          cd examples/gui_project
          ./build.vsh
          mv ./gui_project ./$ARTIFACT
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.ARTIFACT }}
          path: examples/gui_project/${{ env.ARTIFACT }}
