name: macOS

on:
  workflow_call:

jobs:
  setup:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup V
        run: |
          curl -Lo v_macos_arm64.zip https://github.com/vlang/v/releases/latest/download/v_macos_arm64.zip
          unzip -o v_macos_arm64.zip
          mv v ~/v
          ~/v/v symlink
      - run: v install
      - name: Save cache
        uses: actions/cache/save@v4
        with:
          path: |
            ~/v
            ~/.vmodules
          key: ${{ runner.os }}-${{ github.sha }}

  test:
    needs: setup
    strategy:
      matrix:
        cc: [tcc, clang]
        optimization: ['', '-W'] # ['', '-W -cstrict'] # cstrict currently fails with pcre
        exclude:
          - cc: tcc
            optimization: '-W' # ['', '-W -cstrict']
      fail-fast: false
    runs-on: macos-latest
    env:
      VFLAGS: -cg -cc ${{ matrix.cc }} ${{ matrix.optimization }}
    steps:
      - uses: actions/checkout@v4
      - name: Restore cache
        uses: actions/cache/restore@v4
        with:
          path: |
            ~/v
            ~/.vmodules
          key: ${{ runner.os }}-${{ github.sha }}
          fail-on-cache-miss: true
      - name: Setup V
        run: ~/v/v symlink && v -showcc self && v doctor
      - name: Build
        run: v -o lvb .
      - name: Run
        run: ./lvb .
