name: Windows

on:
  workflow_call:

jobs:
  setup:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup V
        shell: bash
        run: |
          curl -Lo v_windows.zip https://github.com/vlang/v/releases/latest/download/v_windows.zip
          7z x v_windows.zip
          mv v ~/v
          ~/v/v symlink
      - run: v install
      - name: Save cache
        uses: actions/cache/save@v4
        with:
          path: |
            ~/v
            ~/.vmodules
          key: ${{ runner.os }}-${{ github.sha }}

  test:
    needs: setup
    strategy:
      matrix:
        cc: [tcc, gcc] # [tcc, gcc, msvc]
        optimization: ['', '-W'] # ['', '-W -cstrict'] # cstrict currently fails with pcre
        exclude:
          - cc: tcc
            optimization: '-W' # ['', '-W -cstrict']
      fail-fast: false
    runs-on: windows-latest
    env:
      VFLAGS: -cg -cc ${{ matrix.cc }}
    steps:
      - uses: actions/checkout@v4
      - name: Restore cache
        uses: actions/cache/restore@v4
        with:
          path: |
            ~/v
            ~/.vmodules
          key: ${{ runner.os }}-${{ github.sha }}
          fail-on-cache-miss: true
      - name: Setup V
        run: |
          ~/v/v symlink
          $env:Path = [System.Environment]::GetEnvironmentVariable("Path","Machine") + ";" + [System.Environment]::GetEnvironmentVariable("Path","User")
          v -showcc self && v doctor
      - name: Build
        run: v ${{ matrix.optimization }} -o lvb.exe . && ls
      - name: Run
        run: ./lvb .
